import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {readAuthorState,inspectAuthorState,authorHtml,AUTHOR_MARKER} from '../src/author.js';

const card={avatar:'demo.png',data:{first_mes:`${AUTHOR_MARKER}\n\n【请选择开场】`,alternate_greetings:['原主开场。','备用开场甲。','备用开场乙。']}};
let swipe=0,last=0;
const helper={getChatMessages:()=>[{role:'assistant',swipe_id:swipe,swipes:[card.data.first_mes,...card.data.alternate_greetings]}],getLastMessageId:()=>last};
const context={characters:[card],characterId:0,groupId:null};
const untouched=JSON.stringify(card);
assert.deepEqual(readAuthorState(context,helper).entries,['原主开场。','备用开场甲。','备用开场乙。']);
assert.equal(JSON.stringify(card),untouched);
assert.match(authorHtml(3),/已读取 3 条正式开场/);
assert.match(authorHtml(3),/data-settings-button/);
assert.match(authorHtml(3),/data-bgm-fields/);
assert.equal((authorHtml(3).match(/id="uos-seed"/g)||[]).length,1);
assert.ok(!authorHtml(3).includes('<script type="module">'));
swipe=1;assert.equal(readAuthorState(context,helper),null);
swipe=0;last=1;assert.equal(readAuthorState(context,helper),null);
last=0;context.groupId=2;assert.equal(readAuthorState(context,helper),null);
context.groupId=null;card.data.first_mes='普通主开场。';assert.equal(readAuthorState(context,helper),null);
assert.match(inspectAuthorState(context,helper).reason,/主开场第一行/);
last=1;assert.equal(inspectAuthorState(context,helper).reason,null);last=0;
card.data.first_mes=AUTHOR_MARKER;card.data.alternate_greetings=[];
assert.match(inspectAuthorState(context,helper).reason,/备用开场为空/);
const payload=JSON.parse(fs.readFileSync('dist/红豆粉开场白选择器_通用脚本_v0.1.0-beta.35.json'));
const remote=fs.readFileSync('remote.js','utf8');
assert.equal(payload.export_with.data,true);
assert.ok(payload.content.length>remote.length,'offline fallback bundles the runtime in the card script');
assert.match(payload.content,/await import\(url\)/);
assert.match(payload.content,/v0\.1\.0-beta\.35\/remote\.js/);
assert.match(payload.content,/function mountBundledSelector\(\)/);
assert.match(payload.content,/远程加载不可用，使用随卡备用代码/);
const fallbackMarker=payload.content.indexOf('\n(async()=>');
assert.ok(fallbackMarker>0);
let fallbackCalls=0,errors=0;
const offlineLoader='function mountBundledSelector(){globalThis.__fallback()}'+payload.content.slice(fallbackMarker);
const sandbox={__fallback:()=>fallbackCalls++,console:{warn:()=>{},error:()=>errors++},document:{}};
vm.runInNewContext(offlineLoader,sandbox,{importModuleDynamically:()=>Promise.reject(new Error('network blocked'))});
await new Promise(resolve=>setTimeout(resolve,0));
assert.equal(fallbackCalls,1,'all blocked CDN imports invoke the bundled runtime');
assert.equal(errors,0,'offline fallback does not report a false fatal error');
assert.match(remote,/function mountAuthorSelector/);
assert.match(remote,/function mountPlayerSelector/);
assert.match(remote,/function mountInDocument/);
assert.match(remote,/api\/characters\/get/);
assert.match(remote,/唯一来源Discord:♡Aliceneko♡\/红豆沙丨本插件完全免费/);
assert.match(remote,/data-uos-watermark/);
assert.match(remote,/pointer-events:auto!important/);
assert.match(remote,/uos-user-search/);
assert.match(remote,/修正标题和登场人物/);
assert.match(remote,/预览完整正文/);
assert.match(remote,/uos-card-names/);
assert.match(remote,/uos-user-version/);
assert.match(remote,/uos-version/);
const source=fs.readFileSync('src/selector.js','utf8');
assert.match(source,/excludedTags:String/);
assert.match(source,/field\('登场人物/);
assert.match(source,/field\('标题中排除的/);
const media={entries:[{title:'开场',image:'data:image/png;base64,YWJj'}],music:{enabled:true,title:'主题曲',audio:'data:audio/mpeg;base64,ZGVm',lyrics:'[00:01]歌词'}};
const exportCard={data:{first_mes:AUTHOR_MARKER,alternate_greetings:['正式开场。'],extensions:{unrelated:{keep:true},universal_opening_selector:media,tavern_helper:{scripts:[payload]}}}};
const imported=JSON.parse(JSON.stringify(exportCard));
assert.deepEqual(imported.data.extensions.universal_opening_selector,media);
assert.deepEqual(imported.data.extensions.unrelated,{keep:true});
assert.equal(imported.data.extensions.tavern_helper.scripts[0].export_with.data,true);
console.log('Remote loader, author card media and round-trip checks passed');
