import assert from 'node:assert/strict';
import fs from 'node:fs';
import {readAuthorState,inspectAuthorState,authorHtml,AUTHOR_MARKER} from '../src/author.js';
import {optimizeCoverData} from '../src/selector.js';

const card={avatar:'demo.png',data:{first_mes:`${AUTHOR_MARKER}\n\n【请选择开场】`,alternate_greetings:['原主开场。','备用开场甲。','备用开场乙。']}};
let swipe=0,last=0;
const helper={getChatMessages:()=>[{role:'assistant',swipe_id:swipe,swipes:[card.data.first_mes,...card.data.alternate_greetings]}],getLastMessageId:()=>last};
const context={characters:[card],characterId:0,groupId:null};
const untouched=JSON.stringify(card);
assert.deepEqual(readAuthorState(context,helper).entries,['原主开场。','备用开场甲。','备用开场乙。']);
assert.equal(JSON.stringify(card),untouched);
assert.match(authorHtml(3),/已读取 3 条正式开场/);
assert.match(authorHtml(3),/data-settings-button/);
assert.match(authorHtml(3),/data-bgm-fields/);
assert.equal((authorHtml(3).match(/id="uos-seed"/g)||[]).length,1);
assert.ok(!authorHtml(3).includes('<script type="module">'));
swipe=1;assert.equal(readAuthorState(context,helper),null);
swipe=0;last=1;assert.equal(readAuthorState(context,helper),null);
last=0;context.groupId=2;assert.equal(readAuthorState(context,helper),null);
context.groupId=null;card.data.first_mes='普通主开场。';assert.equal(readAuthorState(context,helper),null);
assert.match(inspectAuthorState(context,helper).reason,/主开场第一行/);
last=1;assert.equal(inspectAuthorState(context,helper).reason,null);last=0;
card.data.first_mes=AUTHOR_MARKER;card.data.alternate_greetings=[];
assert.match(inspectAuthorState(context,helper).reason,/备用开场为空/);
const payload=JSON.parse(fs.readFileSync('dist/红豆粉开场白选择器_通用脚本_v1.0.8.json'));
const remote=fs.readFileSync('remote.js','utf8');
const sprite=fs.readFileSync('assets/theme-icons.webp');
assert.equal(sprite.toString('ascii',0,4),'RIFF');
assert.equal(sprite.toString('ascii',8,12),'WEBP');
assert.equal(payload.export_with.data,true);
assert.ok(payload.content.length<3000,'import-only loader remains small');
assert.match(payload.content,/await import\(url\)/);
assert.doesNotThrow(()=>new Function(payload.content),'stable loader is valid JavaScript');
assert.doesNotMatch(payload.content,/function mountBundledSelector|function mountPlayerSelector/);
const ref=fs.readFileSync('scripts/runtime-ref.txt','utf8').trim();
assert.match(ref,/^(main|[0-9a-f]{40})$/);
assert.ok(payload.content.includes(`const fallbackRef='${ref}'`));
assert.ok(payload.content.includes('@main/scripts/runtime-ref.txt'));
assert.ok(payload.content.includes("cache:'no-store'"));
assert.ok(payload.content.includes("?cb='+nonce"));
assert.ok(payload.content.includes('Math.floor(Date.now()/300000)'));
assert.ok(payload.content.includes('@${ref}/remote.js'));
assert.match(payload.content,/OPENING_SELECTOR_VERSION/);
assert.doesNotMatch(payload.content,/expected='1\.0\.8'/);
assert.match(remote,/function mountAuthorSelector/);
assert.match(remote,/function mountPlayerSelector/);
assert.match(remote,/function mountInDocument/);
assert.match(remote,/api\/characters\/get/);
assert.match(remote,/唯一来源Discord:♡Aliceneko♡\/红豆粉丨本插件完全免费/);
assert.match(remote,/data-uos-watermark/);
assert.match(remote,/data:image\/webp;base64,[A-Za-z0-9+/]+/);
assert.match(remote,/uos-theme-art/);
assert.match(remote,/uos-theme-swatch-art/);
assert.ok(remote.includes(String.raw`data-tab-art=\"openings\"`));
assert.ok(remote.includes(String.raw`data-tab-art=\"bgm\"`));
assert.ok(remote.includes(String.raw`data-tab-art=\"diagnostics\"`));
assert.match(remote,/uos-empty-music/);
assert.doesNotMatch(remote,/__TAB_(?:OPENINGS|BGM|DIAGNOSTICS)__/);
assert.match(remote,/--uos-empty-opening-art/);
assert.match(remote,/--uos-diagnostics-art/);
assert.match(remote,/showSetupHints:true/);
assert.match(remote,/showSetupHints&&reason&&container&&hasAuthorMarker\(\)/);
assert.match(remote,/--theme-icon-position:100% 50%/);
assert.match(remote,/卷·故事/);
assert.doesNotMatch(remote,/卷 · 故事/);
assert.match(remote,/pointer-events:auto!important/);
assert.match(remote,/uos-user-search/);
assert.match(remote,/修正标题和登场人物/);
assert.match(remote,/预览完整正文/);
assert.match(remote,/uos-card-names/);
assert.match(remote,/uos-user-version/);
assert.match(remote,/uos-version/);
for(const theme of ['starmap','rose','wasteland']){
  assert.match(remote,new RegExp(`data-theme=${theme}`));
  assert.match(remote,new RegExp(`'${theme}'`));
}
assert.ok(remote.includes(String.raw`class=\"uos-background-art\"`));
assert.match(remote,/\.uos-background-art\{[^}]*background-size:cover/);
for(const theme of ['archive','neon','paper','noir','meadow','ancient','starmap','rose','wasteland']){
  assert.ok(remote.includes(String.raw`--uos-theme-bg-${theme}:url(\"data:image/webp;base64,`),theme);
}
assert.ok(remote.includes('THEME_BACKGROUND_IMAGES'));
assert.ok(remote.includes('uos-user-background'));
assert.doesNotMatch(remote,/__THEME_BG_[A-Z]+__/);
const backgroundFiles=['archive','neon','paper','noir','meadow','ancient','starmap','rose','wasteland'].map(theme=>`assets/theme-background-${theme}.webp`);
assert.ok(backgroundFiles.every(file=>fs.statSync(file).size>1000));
assert.ok(backgroundFiles.reduce((sum,file)=>sum+fs.statSync(file).size,0)<350_000);
assert.match(remote,/搜索作者开场/);
const original='data:image/png;base64,'+'x'.repeat(2000);
class MockImage{naturalWidth=1920;naturalHeight=1080;set src(_value){queueMicrotask(()=>this.onload())}}
let dimensions;
const mockDoc={defaultView:{Image:MockImage},createElement:()=>({getContext(){return {drawImage(_image,_x,_y,w,h){dimensions=[w,h]}}},toDataURL(){return 'data:image/webp;base64,YWJj'}})};
assert.equal(await optimizeCoverData(original,{type:'image/png'},mockDoc),'data:image/webp;base64,YWJj');
assert.deepEqual(dimensions,[960,540]);
assert.equal(await optimizeCoverData(original,{type:'image/gif'},mockDoc),original);
assert.equal(await optimizeCoverData('data:image/png;base64,YWJj',{type:'image/png'},mockDoc),'data:image/png;base64,YWJj');
const source=fs.readFileSync('src/selector.js','utf8');
assert.match(source,/excludedTags:String/);
assert.match(source,/field\('登场人物/);
assert.match(source,/field\('标题中排除的/);
const media={entries:[{title:'开场',image:'data:image/png;base64,YWJj'}],music:{enabled:true,title:'主题曲',audio:'data:audio/mpeg;base64,ZGVm',lyrics:'[00:01]歌词'}};
const exportCard={data:{first_mes:AUTHOR_MARKER,alternate_greetings:['正式开场。'],extensions:{unrelated:{keep:true},universal_opening_selector:media,tavern_helper:{scripts:[payload]}}}};
const imported=JSON.parse(JSON.stringify(exportCard));
assert.deepEqual(imported.data.extensions.universal_opening_selector,media);
assert.deepEqual(imported.data.extensions.unrelated,{keep:true});
assert.equal(imported.data.extensions.tavern_helper.scripts[0].export_with.data,true);
console.log('Remote loader, author card media and round-trip checks passed');
