import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';

const dir=fs.mkdtempSync(path.join(os.tmpdir(),'uos-test-'));
const source=path.join(dir,'card.json'), once=path.join(dir,'once.json'), twice=path.join(dir,'twice.json');
const original={name:'Demo',first_mes:'车站最后一班车。',data:{name:'Demo',first_mes:'车站最后一班车。',alternate_greetings:['雨夜的电话。'],extensions:{regex_scripts:[]}}};
fs.writeFileSync(source,JSON.stringify(original));
const pack=path.resolve('pack.mjs');
execFileSync(process.execPath,[pack,source,once]);
const card=JSON.parse(fs.readFileSync(once));
assert.equal(card.data.alternate_greetings.length,2);
assert.equal(card.data.alternate_greetings[0],original.first_mes);
assert.match(card.data.first_mes,/UniversalOpeningSelector/);
assert.equal(card.data.extensions.regex_scripts.length,1);
assert.equal(card.data.extensions.universal_opening_selector.entries.length,2);
const regex=card.data.extensions.regex_scripts[0];
assert.match(regex.replaceString,/data-settings-button/);
assert.match(regex.replaceString,/data-theme-button/);
assert.match(regex.replaceString,/Aliceneko-Opening-Selector@v0\.1\.0-beta\.3\/index\.js/);
assert.doesNotMatch(regex.replaceString,/function mountInDocument/);
card.data.extensions.universal_opening_selector.entries[0].image='data:image/png;base64,YWJj';
card.data.extensions.universal_opening_selector.music={title:'Demo',audio:'data:audio/mpeg;base64,ZGVm',lyrics:'[00:01]一句歌词'};
fs.writeFileSync(once,JSON.stringify(card));
execFileSync(process.execPath,[pack,once,twice]);
const result=JSON.parse(fs.readFileSync(twice));
assert.equal(result.data.alternate_greetings.length,2);
assert.equal(result.data.extensions.regex_scripts.length,1);
assert.equal(result.data.extensions.universal_opening_selector.entries[0].image,'data:image/png;base64,YWJj');
assert.equal(result.data.extensions.universal_opening_selector.music.audio,'data:audio/mpeg;base64,ZGVm');
assert.equal(result.data.extensions.universal_opening_selector.music.lyrics,'[00:01]一句歌词');
fs.rmSync(dir,{recursive:true,force:true});
console.log('Pack and round-trip checks passed');
