import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';

const dir=fs.mkdtempSync(path.join(os.tmpdir(),'uos-test-'));
const source=path.join(dir,'card.json'), once=path.join(dir,'once.json'), twice=path.join(dir,'twice.json');
const original={name:'Demo',first_mes:'车站最后一班车。',data:{name:'Demo',first_mes:'车站最后一班车。',alternate_greetings:['雨夜的电话。'],extensions:{regex_scripts:[]}}};
fs.writeFileSync(source,JSON.stringify(original));
const pack=path.resolve('pack.mjs');
execFileSync(process.execPath,[pack,source,once]);
const card=JSON.parse(fs.readFileSync(once));
assert.equal(card.data.alternate_greetings.length,2);
assert.equal(card.data.alternate_greetings[0],original.first_mes);
assert.match(card.data.first_mes,/UniversalOpeningSelector/);
assert.equal(card.data.extensions.regex_scripts.length,1);
assert.equal(card.data.extensions.universal_opening_selector.entries.length,2);
assert.equal(card.data.extensions.universal_opening_selector.music.enabled,false);
const regex=card.data.extensions.regex_scripts[0];
assert.match(regex.replaceString,/data-settings-button/);
assert.match(regex.replaceString,/data-theme-button/);
assert.match(regex.replaceString,/Aliceneko-Opening-Selector@v0\.1\.0-beta\.26\/index\.js/);
assert.match(regex.replaceString,/data-tab="bgm"/);
assert.match(regex.replaceString,/data-tab="diagnostics"/);
assert.match(regex.replaceString,/data-diagnostics/);
assert.match(regex.replaceString,/<style id="uos-css">[\s\S]*?\.uos-fields/);
assert.match(regex.replaceString,/\.uos\{border-radius:0!important;box-shadow:none!important\}/);
for(const theme of ['archive','neon','paper','noir','meadow','ancient'])assert.match(regex.replaceString,new RegExp(`\\.uos\\[data-theme=${theme}\\]`));
assert.match(regex.replaceString,/data-music-title/);
assert.match(regex.replaceString,/function mountInDocument/);
assert.match(regex.replaceString,/查看原开场正文/);
assert.match(regex.replaceString,/从原文生成文案建议/);
assert.match(regex.replaceString,/uos-theme-swatch/);
assert.match(regex.replaceString,/data-top-status/);
execFileSync(process.execPath,['--check',path.resolve('src/selector.js')]);
const moduleScript=regex.replaceString.match(/<script type="module">([\s\S]*?)<\/script>/)?.[1];
assert.ok(moduleScript);
const checked=path.join(dir,'inline.mjs');fs.writeFileSync(checked,moduleScript);execFileSync(process.execPath,['--check',checked]);
assert.equal(regex.findRegex,'<UniversalOpeningSelector/>');
assert.deepEqual(regex.placement,[2]);
assert.equal(regex.disabled,false);
const helper=card.data.extensions.tavern_helper;
assert.equal(helper.scripts.length,1);
assert.equal(helper.scripts[0].enabled,true);
assert.match(helper.scripts[0].content,/Aliceneko-Opening-Selector@v0\.1\.0-beta\.26\/index\.js/);
assert.match(helper.scripts[0].content,/mountOpeningSelector\(globalThis\.\$\?\.\('body'\)/);
assert.equal(helper.scripts[0].export_with.data,true);
card.data.extensions.universal_opening_selector.entries[0].image='data:image/png;base64,YWJj';
card.data.extensions.universal_opening_selector.music={enabled:true,title:'Demo',audio:'data:audio/mpeg;base64,ZGVm',lyrics:'[00:01]一句歌词'};
fs.writeFileSync(once,JSON.stringify(card));
execFileSync(process.execPath,[pack,once,twice]);
const result=JSON.parse(fs.readFileSync(twice));
assert.equal(result.data.alternate_greetings.length,2);
assert.equal(result.data.extensions.regex_scripts.length,1);
assert.equal(result.data.extensions.tavern_helper.scripts.length,1);
assert.equal(result.data.extensions.tavern_helper.scripts[0].id,helper.scripts[0].id);
assert.equal(result.data.extensions.universal_opening_selector.entries[0].image,'data:image/png;base64,YWJj');
assert.equal(result.data.extensions.universal_opening_selector.music.audio,'data:audio/mpeg;base64,ZGVm');
assert.equal(result.data.extensions.universal_opening_selector.music.enabled,true);
assert.equal(result.data.extensions.universal_opening_selector.music.lyrics,'[00:01]一句歌词');
fs.rmSync(dir,{recursive:true,force:true});
console.log('Pack and round-trip checks passed');
