import assert from 'node:assert/strict';
import {readPlayerState} from '../index.js';

const character={avatar:'example.png',data:{first_mes:'第一条开场。',alternate_greetings:['第二条开场。','第三条开场。']}};
const context={characters:[character],characterId:0,groupId:null};
let swipeId=0,lastId=0;
const helper={getChatMessages:()=>[{role:'assistant',swipe_id:swipeId,swipes:[character.data.first_mes,...character.data.alternate_greetings]}],getLastMessageId:()=>lastId,setChatMessages:async()=>{}};
const state=readPlayerState(context,helper);
assert.deepEqual(state.entries.map(x=>x.index),[0,1,2]);
assert.equal(state.entries[0].body,'第一条开场。');
assert.equal(state.entries[2].body,'第三条开场。');
assert.equal(state.entries[0].title,'第一条开场。');
assert.equal(state.entries[0].description,'');
character.data.first_mes='<status>时间：凌晨；地点：车站</status>\n<角色档案>她带着两张车票。</角色档案>\n<正文>雨停以后，站台只剩下一盏灯。她在等你。</正文>';
character.data.alternate_greetings[0]='```yaml\ntime: midnight\n```\n<时间>凌晨</时间>\n<地点>电话亭</地点>\n<content>凌晨的电话铃响起。屏幕上的名字很熟悉。</content>';
const tagged=readPlayerState(context,helper);
assert.equal(tagged.entries[0].title,'雨停以后，站台只剩下一盏灯。');
assert.equal(tagged.entries[1].title,'凌晨的电话铃响起。');
assert.equal(tagged.entries[0].body,character.data.first_mes);
assert.deepEqual(tagged.entries[0].names,[]);
character.data.first_mes='<角色档案>姓名：沈挽昼\n年龄：23</角色档案>\n<正文>雨停以后，她站在车站。</正文>';
character.data.alternate_greetings[0]='<content>电话响了。\n沈挽昼：别开门。\n地点：旧车站</content>';
const named=readPlayerState(context,helper);
assert.deepEqual(named.entries[0].names,['沈挽昼']);
assert.deepEqual(named.entries[1].names,['沈挽昼']);
assert.equal(named.entries[0].title,'雨停以后，她站在车站。');
character.data.first_mes='<scene>只用于设定的内容。</scene>';
assert.equal(readPlayerState(context,helper).entries[0].title,'开场 1');
character.data.first_mes='第一条开场。';
character.data.alternate_greetings[0]='第二条开场。';
swipeId=2;
assert.equal(readPlayerState(context,helper).swipeId,2);
lastId=1;
assert.equal(readPlayerState(context,helper),null);
lastId=0;
character.data.first_mes='<UniversalOpeningSelector/>';
assert.equal(readPlayerState(context,helper),null);
character.data.first_mes='第一条开场。';
context.groupId=1;
assert.equal(readPlayerState(context,helper),null);
console.log('Player mode maps ordinary greetings and guards active chats');
